---
title: Python and R together
format: 
    html:
        toc: true
        toc-location: right
        code-tools: true
        anchor-sections: true
author: Klaus G.
date: today
from: markdown+emoji
---

## Starting with R code
```{r}
#| label: load_R_libraries
#| echo: true
#| output: false
library(reticulate)
library(ggplot2)
# github Actions workflow is with the current publish.yml no setting up a venv
# **uncomment** the following line if you run it in VSCode
#use_virtualenv("./.venv", required=TRUE)  # tells R reticulate to use this Python virtual envivonment
```

```{r}
#| label: load_df_to_R
df_r <- read.csv("./data/covid.csv")
nrow(df_r)
```

## Some Python code
```{python}
#| label: pandas_and_python_df
import pandas as pd

df_python_covid = pd.read_csv("./data/covid.csv")
df_python_covid.shape
df_python_covid.isna().sum()
df_python_covid.dropna(inplace=True)
df_python_covid.isna().sum()
df_python_covid_agg = df_python_covid.groupby('state')['deaths'].sum()
df_python_covid_agg.head(5)
df_python_covid_agg.index
```

## How to exchange dataframes between Python and R

* [Python to R](https://stackoverflow.com/questions/74081417/how-to-visualize-a-pandas-dataframe-in-r-chunk-quarto)
* [R to Python](https://www.r-bloggers.com/2023/01/combining-r-and-python-with-reticulate-and-quarto/)

```{r}
#| label: in_R_work_with_pandas_df
# R code
nrow(reticulate::py$df_python_covid)
back_to_r = reticulate::py$df_python_covid_agg
head(back_to_r, 5)
```

```{python}
#| label: access_R_df_in_python
# Python code
type(r.df_r)
```

## Multi-index example
mpg - miles per gallon - is a dataset included in R 
```{r}
#| label: print_R_mpg_dataset
# R code
head(mpg,5)
```

```{python}
#| label: group_python_mpg_df
# Python code
df_mpg = r.mpg
#df_mpg.shape
#df_mpg.info()
df_mpg_grouped = df_mpg.groupby(['manufacturer','class'])['year'].value_counts()
df_mpg_grouped_reset_index = df_mpg_grouped.reset_index()
df_mpg_grouped.head(5)
df_mpg_grouped_reset_index.head(5)
```

```{r}
#| label: demonstrate_multiindex_in_R
# R code
head(reticulate::py$df_mpg_grouped, 5)  # multi-index
print("---------")
head(reticulate::py$df_mpg_grouped_reset_index, 5)  # collapsed multi-index
#reticulate::py_last_error()
```