---
title: Python and R together
format: html
---

## R code
```{r}
#| label: load_R_libraries
library(tidyverse)
library(reticulate)
use_virtualenv("./.venv", required=TRUE)  #tells R reticulate to use this Python virtual envivonment
```

```{r}
#| label: load_df_to_R
df_r <- read.csv("./data/covid.csv")
nrow(df_r)
```

## Python code
```{python}
import pandas as pd

df_python_covid = pd.read_csv("./data/covid.csv")
df_python_covid.shape
df_python_covid.isna().sum()
df_python_covid.dropna(inplace=True)
df_python_covid.isna().sum()
df_python_covid_agg = df_python_covid.groupby('state')['deaths'].sum()
df_python_covid_agg.index
```

## How to exchange dataframes between Python and R
(Python to R)[https://stackoverflow.com/questions/74081417/how-to-visualize-a-pandas-dataframe-in-r-chunk-quarto]
(R to Python)[https://www.r-bloggers.com/2023/01/combining-r-and-python-with-reticulate-and-quarto/]

```{r}
nrow(reticulate::py$df_python_covid)
back_to_r = reticulate::py$df_python_covid_agg
back_to_r
```

```{python}
type(r.df_r)
```

## Multi-index example
mpg - miles per gallon - is a dataset included in R 
```{r}
mpg
```

```{python}
df_mpg = r.mpg
#df_mpg.shape
#df_mpg.info()
df_mpg_grouped = df_mpg.groupby(['manufacturer','class'])['year'].value_counts()
df_mpg_grouped_reset_index = df_mpg_grouped.reset_index()
print(df_mpg_grouped)
print(df_mpg_grouped_reset_index)
```

```{r}
reticulate::py$df_mpg_grouped  #multi-index
print("---------")
reticulate::py$df_mpg_grouped_reset_index  #collapsed multi-index
#reticulate::py_last_error()
```